services:
  web-dev:
    container_name: adaptive-learning-webapp-dev
    image: ghcr.io/ec061/adaptive_learning_webapp:dev-latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    pull_policy: always
    ports:
      - "3001:3000"
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DEV_DATABASE_URL}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
